#!/usr/bin/env bash

###                                                ###
# - Only run this file from the dotfiles repo root - #
###                                                ###

cp $HOME/.zshrc .
cp $HOME/.tmux.conf . 
