#!/usr/bin/env bash

###                                                ###
# - Only run this file from the dotfiles repo root - #
###                                                ###

cp ~/.zshrc ./.zshrc-tmpl
cp ~/.vimrc ./.vimrc
cp ~/.tmux.conf ./.tmux.conf
