#!/usr/bin/env bash

###                                                ###
# - Only run this file from the dotfiles repo root - #
###                                                ###

cp ~/.zshrc .
cp ~/.tmux.conf . 
